FROM node:20.13.0-alpine

# Install pnpm
RUN npm i -g pnpm@^9.0.0

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json pnpm-lock.yaml ./

# Install project dependencies
RUN pnpm install

# Copy project files to the working directory
COPY . .

# Build and remove devDependencies pacakges
RUN npm run tsc && pnpm prune --prod

# Expose the port on which the application runs
EXPOSE 3002

# Start the application
# CMD ["npm", "run", "start:docker"]
CMD ["npm", "run", "start:container"]