FROM node:18.20.2-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy project files to the working directory
COPY . .

# Expose the port on which the application runs
EXPOSE 3001

# Start the application
CMD ["npm", "start"]
