. "$PSScriptRoot\base-parameter.ps1"
. "$PSScriptRoot\download.ps1"
. "$PSScriptRoot\env-path.ps1"
. "$PSScriptRoot\log.ps1"
. "$PSScriptRoot\msiexec.ps1"
. "$PSScriptRoot\tar.ps1"
. "$PSScriptRoot\version.ps1"
