version: '3'

services:
  jenkins:
    user: root # This parameter must exist, otherwise automatic updates cannot be performed.
    platform: linux/amd64
    image: jenkinsci/blueocean:1.25.7
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      all:
        aliases:
          - jenkins
    volumes:
      - ../temp/jenkins/home:/var/jenkins_home
      - ../temp/jenkins/docker.sock:/var/run/docker.sock
      - ../temp/jenkins/key:/root/.ssh

networks:
  all:
