version: "3"

services:
  nginx:
    platform: linux/amd64
    image: nginx:1.27-alpine
    restart: always
    ports:
      - 5174-5179:5174-5179
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/logs:/var/log/nginx
      - ../nginx/website:/website
