version: "3"

services:
  nexus:
    user: root
    platform: linux/amd64
    image: sonatype/nexus3:3.66.0
    restart: always
    networks:
      all:
        aliases:
          - nexus
    ports:
      - 8081:8081
    volumes:
      - ../temp/nexus/data:/nexus-data

    # # Adjust to run properly in environments with limited memory.
    # mem_limit: 2g
    # environment:
    #   INSTALL4J_ADD_VM_PARAMS: -Xms128m -Xmx512m -XX:MaxDirectMemorySize=512m -Djava.util.prefs.userRoot=/nexus-data/javaprefs


networks:
  all: