# Use Node.js image as the build stage
FROM node:20.13.0 AS build-stage

# Install pnpm
RUN npm i -g pnpm@^9.0.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json pnpm-lock.yaml ./

# Install project dependencies
RUN pnpm install

# Copy project files to the working directory
COPY . .

# Build and remove devDependencies packages
RUN npm run build && rm -rf /app/node_modules

# Use Nginx image as the production stage
FROM nginx:1.27-alpine AS production-stage

# Copy custom Nginx configuration files
COPY nginx-conf/nginx.conf   /etc/nginx/nginx.conf
COPY nginx-conf/conf.d/*     /etc/nginx/conf.d/

# Copy built files to Nginx's default static file directory
COPY --from=build-stage /app/dist /website

# Expose the port on which the application runs
EXPOSE 5173-5179

# Start the application
CMD ["nginx", "-g", "daemon off;"]
